#!/usr/bin/env python3
"""Write AI image-generation prompts for handoff mockups — no PNGs in the skill package."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from _heyeddi_paths import designs_dir
from _product_schema import load_json, product_json_path
from _skill_cli import emit, fail, resolve_project_root
from _wireframe_layouts import page_context_from_product


def _prompt_desktop(ctx) -> str:
    return (
        f"UI mockup wireframe-quality layout reference for {ctx.product_name}, route {ctx.route}. "
        f"Purpose: {ctx.purpose}. "
        f"Desktop 1440px wide, calm modern SaaS, clear hierarchy — NOT a generic admin template. "
        f"Show app chrome, page title, primary content regions, one primary CTA. "
        f"Grayscale-friendly layout; no logo watermark. "
        f"Persona success feeling: {ctx.success_feeling or 'clear and trustworthy'}."
    )


def _prompt_mobile(ctx) -> str:
    return (
        f"Mobile UI mockup 390px wide for {ctx.product_name}, route {ctx.route}. "
        f"Same information architecture as desktop, stacked for mobile. "
        f"Purpose: {ctx.purpose}. Top bar, content cards, full-width primary action. "
        f"Layout reference only — not final brand colors."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare AI mockup image prompts (agent generates PNGs)")
    parser.add_argument("--project-root", default=None)
    parser.add_argument("--feature", required=True)
    parser.add_argument("--route", default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    root = resolve_project_root(args.project_root)
    json_path = product_json_path(root)
    if not json_path.is_file():
        fail(f"missing {json_path.relative_to(root)} — run write_product first")

    data = load_json(json_path)
    ctx = page_context_from_product(data, feature=args.feature, route=args.route)
    out_dir = designs_dir(root) / args.feature
    prompts_path = out_dir / "mockup-prompts.json"

    if prompts_path.is_file() and not args.force:
        emit(json.dumps({"status": "skipped", "path": str(prompts_path)}, indent=2))
        return

    payload = {
        "feature": args.feature,
        "route": ctx.route,
        "product_name": ctx.product_name,
        "purpose": ctx.purpose,
        "generated_by": "product-translator",
        "instructions": [
            "Use native image generation (or user-provided screenshots via ingest_mockups).",
            "Do NOT use bundled Pillow/template PNGs — they are not part of this skill.",
            "Save outputs as desktop.png and mobile.png in this folder after generation.",
            "Then run seed_brief --force and refine mockup-brief.md from the images.",
        ],
        "prompts": {
            "desktop": _prompt_desktop(ctx),
            "mobile": _prompt_mobile(ctx),
        },
        "output_files": ["desktop.png", "mobile.png"],
    }

    if args.dry_run:
        emit(json.dumps({"status": "dry_run", "prompts": payload["prompts"]}, indent=2))
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    prompts_path.write_text(json.dumps(payload, indent=2) + "\n")

    handoff = {
        "route": ctx.route,
        "app": ctx.product_name,
        "mode": "screenshot",
        "fidelity": "ai_generated_pending",
        "mockup_contract": "ai_image_prompts",
        "generated_by": "product-translator",
        "notes": [
            "PNG files must be generated by agent via AI or ingested from user — not shipped with skill",
            "See mockup-prompts.json for desktop/mobile prompts",
        ],
    }
    (out_dir / "handoff.json").write_text(json.dumps(handoff, indent=2) + "\n")

    emit(
        json.dumps(
            {
                "status": "ok",
                "path": str(prompts_path.relative_to(root)),
                "next": "Generate desktop.png + mobile.png with AI using prompts, then seed_brief --force",
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
